version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/FirstNodeApp

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 30000
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 30000
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 30000
  ValidateService:
    - location: scripts/validate_server.sh
      timeout: 30000
      runas: root
