trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build --if-present
    npm run test --if-present
  displayName: 'npm install, build and test'

- task: CopyFiles@2
  inputs:
    Contents: '**' ## update to match what you want to copy
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
